Allow annotations on enums
flix/flix pull request #3290
Opened 2022-03-07 00:31 UTC by nicdard

Partially address https://github.com/flix/flix/issues/2831

I just encoded enums to start looking into the issue and get some initial feedback, in a following PR I will do the same also for classes and type aliases.

This PR builds on top of: https://github.com/flix/flix/pull/3289

2022-03-07 15:35 UTC, magnus-madsen commented
@mlutze Can you take an initial look? Thanks!

2022-03-07 16:16 UTC, mlutze requested changes
Looks good! Just a couple little things.

2022-03-08 08:29 UTC, nicdard commented on main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala
> +    // Visit every definition in the program in parallel and transform to type 'OccurrenceAst.Def'
Oh sorry

2022-03-08 08:30 UTC, nicdard commented on main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
> +        val sAnn = if (ann.isEmpty) Ast.Annotations.Empty else Ast.Annotations(ann.map(a => a.name))
Yes I was also wondering about this, so I will change it, should I also change it in the other point of the code for consistency?

2022-03-08 08:32 UTC, mlutze commented on main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
> +        val sAnn = if (ann.isEmpty) Ast.Annotations.Empty else Ast.Annotations(ann.map(a => a.name))
Yes please :)

2022-03-08 08:54 UTC, mlutze approved these changes

2022-03-10 12:39 UTC, magnus-madsen reviewed
Looks good. I added one small comment.

One thing that is missing: We should use these annotations in `Documentor`. See here how it is done for defs: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Documentor.scala#L116

We should also use the annotations in LSP, e.g. if something is marked deprecated we should show it. That happens in `CodeHinter`.

2022-03-10 12:39 UTC, magnus-madsen commented on main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> +        case (mod, ann, tparams) =>
i.e. flatMapN(annVal, modVal, ...)

2022-03-14 11:27 UTC, nicdard commented on main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> +        case (mod, ann, tparams) =>
Thanks!

2022-03-15 16:00 UTC, merged

2022-03-15 16:08 UTC, nicdard commented
> Excellent! Glad to have this merged in :)

I will also port the suggestions to https://github.com/flix/flix/pull/3294 as they are similar :)