refactor: make zipWithIndex and enumerator consistent with mapWithIndex (issue #5080)
flix/flix pull request #5201
Opened 2022-12-29 18:41 UTC by stephentetley

This PR changes the argument orders of `zipWithIndex` and `enumerator` so they match `mapWithIndex` - see issue #5080

I think `zipWithIndex` with index first is a good improvement over the status quo - a list of (index, value) pairs seems consistent with how we represent other data e.g. Map (key, value) pairs rather than (value, index) pairs.

Similarly a `foreach` comprehension with an `enumerator` seems more consistent with a traditional for-loop if the loop variables are in (index, value) order.

2022-12-29 22:14 UTC, JonathanStarup requested changes
I found some comments that reference the pair order

2022-12-29 22:14 UTC, JonathanStarup commented on main/src/library/Chain.flix
>      /// Returns a chain where each element `e` is mapped to `(e, i)` where `i`
The doc comment is outdated here

2022-12-29 22:14 UTC, JonathanStarup commented on main/src/library/DelayList.flix
>      ///
Heres also a comment

2022-12-29 22:14 UTC, JonathanStarup commented on main/src/library/List.flix
>      /// Returns a list where each element `e` is mapped to `(e, i)` where `i`
Here is also a comment

2022-12-29 22:14 UTC, JonathanStarup commented on main/src/library/Nec.flix
>      /// Returns a Nec where each element `e` is mapped to `(e, i)` where `i`
^

2022-12-29 22:14 UTC, JonathanStarup commented on main/src/library/Nel.flix
>      /// Returns a new non-empty list where each element `e` is mapped to `(e, i)`
^

2022-12-30 09:37 UTC, stephentetley commented
Thanks for the review Jonathan - I'll get those comments sorted today.

2022-12-30 10:24 UTC, stephentetley commented on main/src/library/DelayList.flix
>      ///
fixed

2022-12-30 10:24 UTC, stephentetley commented on main/src/library/List.flix
>      /// Returns a list where each element `e` is mapped to `(e, i)` where `i`
fixed

2022-12-30 10:24 UTC, stephentetley commented on main/src/library/Nec.flix
>      /// Returns a Nec where each element `e` is mapped to `(e, i)` where `i`
fixed

2022-12-30 10:24 UTC, stephentetley commented on main/src/library/Nel.flix
>      /// Returns a new non-empty list where each element `e` is mapped to `(e, i)`
fixed

2022-12-30 10:48 UTC, JonathanStarup approved these changes

2022-12-30 11:20 UTC, merged

2022-12-30 11:20 UTC, magnus-madsen commented
Thanks guys!